### ISSUE TITLE
Need access to "required" fields for field in component

### ISSUE THREAD

**Issue by paulhoule** [FIXTradingCommunity/pyfixorchestra#1]
Information about which fields are required in a component are in the Orchestra XML file:

```
<fixr:component name="StandardHeader" id="1024" category="Session" added="FIX.4.0" abbrName="BaseHeader">
   <fixr:fieldRef id="8" presence="required" added="FIX.4.0">
    ...
    </fixr:fieldRef>
</fixr:component>
```

but I am not seeing this information when I do

```
FixDictionary("fixr:components").generateDictionary()
```

It seems that this distinction could be made for fields that are part of a group but I don't see it in the XML file.

In the XML file the "required" property is stuck to the the component-field connection.  We couldn't represent the information about those relationships as a list of integers anymore,  but we could either have

1. [{"fieldId": "532", "presence": "required"}, ...] or
2. {"fieldIds": [532, ...], "presences": ["required", ...] }

if we represent the presence field in fixr:components dictionary.  It could be a property of the fixr:field dictionary IF we know that one field only appears in at most one component.  See

https://en.wikipedia.org/wiki/AoS_and_SoA

**Comment by donmendelson** [comment]
Presence is correctly viewed as a relationship of a member to its container, not a permanent property of the member itself. A field might be required in one message but optional in another.
